# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2018-09-27 02:51
from __future__ import unicode_literals

from django.db import migrations, models
import phone_field.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='PatientProfile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(max_length=100)),
                ('gender', models.CharField(choices=[('m', 'Male'), ('f', 'Female')], max_length=10)),
                ('age', models.CharField(max_length=10)),
                ('address', models.CharField(max_length=50)),
                ('contact', phone_field.models.PhoneField(max_length=100)),
            ],
        ),
    ]
