# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2018-11-13 03:40
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('patientinfo', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Medicine',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('medicine_name', models.CharField(max_length=100)),
                ('start_date', models.DateField(max_length=50)),
                ('dose', models.CharField(max_length=50)),
                ('end_date', models.DateField(max_length=50)),
            ],
        ),
    ]
