# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2019-01-17 03:25
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('patientinfo', '0005_auto_20190116_1014'),
    ]

    operations = [
        migrations.RenameField(
            model_name='patientprofile',
            old_name='full_name',
            new_name='fullname',
        ),
        migrations.AddField(
            model_name='patientprofile',
            name='image',
            field=models.ImageField(default=1, upload_to='media/'),
        ),
    ]
