# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2019-01-17 03:57
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('doctorinfo', '0013_auto_20190114_1003'),
        ('patientinfo', '0006_auto_20190117_0910'),
    ]

    operations = [
        migrations.CreateModel(
            name='MakeAppointment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('symptom', models.TextField(max_length=1000)),
                ('availabledate', models.DateField()),
                ('availabletime', models.TimeField()),
                ('doctorname', models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='doctorinfo.DoctorProfile')),
            ],
        ),
        migrations.RenameField(
            model_name='patientprofile',
            old_name='related_doc',
            new_name='doctorname',
        ),
    ]
