# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2019-02-04 04:28
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('patientinfo', '0007_auto_20190117_0942'),
    ]

    operations = [
        migrations.AlterField(
            model_name='patientprofile',
            name='contact',
            field=models.CharField(max_length=100),
        ),
    ]
