# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2019-02-10 07:50
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('patientinfo', '0012_auto_20190210_1126'),
    ]

    operations = [
        migrations.AlterField(
            model_name='medicine',
            name='comment',
            field=models.CharField(max_length=200),
        ),
    ]
