# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2019-02-10 10:29
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('patientinfo', '0014_makeappointment_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='medicine',
            name='image',
            field=models.FileField(default=1, upload_to='media/'),
        ),
        migrations.AddField(
            model_name='medicine',
            name='user',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
