# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2019-02-10 10:40
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('patientinfo', '0015_auto_20190210_1614'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='medicine',
            name='image',
        ),
    ]
