# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2019-02-10 10:42
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('patientinfo', '0016_remove_medicine_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='medicine',
            name='start_date',
            field=models.CharField(max_length=50),
        ),
    ]
