# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2018-12-13 15:21
from __future__ import unicode_literals

import ckeditor.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('contactus', '0002_auto_20181213_2105'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contactus',
            name='message',
            field=ckeditor.fields.RichTextField(),
        ),
    ]
