# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2018-12-16 02:38
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contactus', '0003_auto_20181213_2106'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contactus',
            name='message',
            field=models.CharField(max_length=100),
        ),
    ]
