# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2018-12-20 02:51
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contactus', '0004_auto_20181216_0823'),
    ]

    operations = [
        migrations.CreateModel(
            name='CV',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('cv_file', models.FileField(upload_to='cv/')),
            ],
        ),
    ]
