# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2018-12-20 04:42
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contactus', '0005_cv'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cv',
            name='cv_file',
            field=models.ImageField(upload_to='cv/'),
        ),
    ]
