# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2019-01-29 04:03
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contactus', '0006_auto_20181220_1027'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cv',
            name='cv_file',
            field=models.CharField(max_length=100),
        ),
    ]
