# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2019-01-29 04:11
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contactus', '0007_auto_20190129_0948'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cv',
            name='cv_file',
            field=models.FileField(upload_to='cv/'),
        ),
    ]
