# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2018-11-20 04:18
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('doctorinfo', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='comment',
            name='doctor_id',
        ),
        migrations.RemoveField(
            model_name='comment',
            name='patient_id',
        ),
        migrations.DeleteModel(
            name='Comment',
        ),
    ]
