# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2018-12-10 04:46
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('doctorinfo', '0005_auto_20181210_1022'),
    ]

    operations = [
        migrations.AlterField(
            model_name='doctorprofile',
            name='image',
            field=models.ImageField(upload_to='media/'),
        ),
    ]
