# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2018-12-17 03:19
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('doctorinfo', '0006_auto_20181210_1031'),
    ]

    operations = [
        migrations.AddField(
            model_name='department',
            name='image',
            field=models.ImageField(default=1, upload_to='media/'),
        ),
    ]
