# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2018-12-17 04:24
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('doctorinfo', '0007_department_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='department',
            name='description',
            field=models.TextField(default=1, max_length=1000),
        ),
    ]
