# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2018-12-17 04:34
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('doctorinfo', '0008_department_description'),
    ]

    operations = [
        migrations.AlterField(
            model_name='department',
            name='description',
            field=models.TextField(max_length=1000),
        ),
        migrations.AlterField(
            model_name='department',
            name='image',
            field=models.ImageField(upload_to='media/'),
        ),
    ]
