# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2019-01-14 04:16
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('doctorinfo', '0011_auto_20181219_1741'),
    ]

    operations = [
        migrations.AlterField(
            model_name='doctorprofile',
            name='specialization',
            field=models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, to='doctorinfo.Department'),
        ),
    ]
