# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2019-01-14 04:18
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('doctorinfo', '0012_auto_20190114_1001'),
    ]

    operations = [
        migrations.AlterField(
            model_name='doctorprofile',
            name='specialization',
            field=models.CharField(max_length=100),
        ),
    ]
