# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2019-01-29 03:28
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('doctorinfo', '0013_auto_20190114_1003'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='doctorprofile',
            name='age',
        ),
        migrations.AddField(
            model_name='doctorprofile',
            name='date_of_birth',
            field=models.CharField(default=1, max_length=10),
        ),
    ]
