# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2019-02-04 04:28
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('doctorinfo', '0014_auto_20190129_0913'),
    ]

    operations = [
        migrations.AlterField(
            model_name='doctorprofile',
            name='contact',
            field=models.CharField(max_length=50),
        ),
    ]
