# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2019-02-04 04:49
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('doctorinfo', '0015_auto_20190204_1013'),
    ]

    operations = [
        migrations.CreateModel(
            name='PatientList',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fullname', models.CharField(max_length=100)),
                ('address', models.CharField(max_length=50)),
                ('contact', models.CharField(max_length=100)),
            ],
        ),
    ]
