# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2018-12-10 04:01
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myaccount', '0002_auto_20181209_0916'),
    ]

    operations = [
        migrations.RenameField(
            model_name='userprofile',
            old_name='full_name',
            new_name='fullname',
        ),
    ]
