# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2018-12-24 04:30
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myaccount', '0003_auto_20181210_0946'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userprofile',
            name='re_password',
        ),
    ]
