# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2019-01-14 03:55
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myaccount', '0005_userprofile__is_staff'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='fullname',
            field=models.CharField(max_length=100),
        ),
    ]
