# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2019-01-25 03:00
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myaccount', '0006_auto_20190114_0940'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='image',
            field=models.ImageField(default=1, upload_to='media/'),
        ),
    ]
