# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2019-02-05 04:20
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myaccount', '0007_userprofile_image'),
    ]

    operations = [
        migrations.RenameField(
            model_name='userprofile',
            old_name='phone_num',
            new_name='contact',
        ),
    ]
