# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2019-02-05 04:28
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myaccount', '0008_auto_20190205_1005'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='image',
            field=models.ImageField(upload_to='media/'),
        ),
    ]
