# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2019-02-10 07:14
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myaccount', '0011_remove_userprofile_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='age',
            field=models.CharField(default=0, max_length=50),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='gender',
            field=models.CharField(choices=[('m', 'Male'), ('f', 'Female')], default=0, max_length=10),
        ),
    ]
