# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2019-02-10 07:17
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myaccount', '0012_auto_20190210_1259'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='gender',
            field=models.CharField(choices=[('Male', 'Male'), ('Female', 'Female')], default=0, max_length=10),
        ),
    ]
