# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2018-11-20 04:18
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('doctorinfo', '0002_auto_20181120_1003'),
    ]

    operations = [
        migrations.CreateModel(
            name='Comment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('comments', models.TextField(max_length=200)),
                ('date', models.DateField(max_length=10)),
                ('doctor_id', models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='doctorinfo.DoctorProfile')),
            ],
        ),
    ]
